### ISSUE TITLE
Module better-sqlite3 not found

### ISSUE THREAD

**Issue by SathvikHegde** [RedLukeBug/discord-prefix#1]
I have been trying to compile and I get the error the error better-sqlite3 not found.

I installed it and it seems to work.

Shouldnt better sqlite3 be added as a dependancy?

update it
Thanks.

**Comment by RedLukeBug** [comment]
Hello. Yes, whenever you install discord-prefix it will attempt to install
sqlite as a dependency but sometimes an error can occur during
installation. I can help you debug. What happens when you run `npm ls
better-sqlite3`?

**Comment by SathvikHegde** [comment]
When I run "npm i better-sqlite3" It tells me that vs studio was not found. I have installed it but I am having trouble adding it to the path.

Is there any prebuilt version of better sqlite3?

**Comment by RedLukeBug** [comment]
Could you join my discord server then dm me? I'm Dark Knight#0001 and the
discord is on the npm page. I could help you there.

**Comment by RedLukeBug** [comment]
Issue has been fixed by adding better-sqlite3 as a native dependency.
